Gestion de la requête pour un utilisateur
2022-d04-java-fs/gestion-des-transports-back pull request #7
Opened 2022-07-08 15:50 UTC by JeremyPayet

2022-07-11 10:07 UTC, Axurynn requested changes

2022-07-11 10:08 UTC, Axurynn requested changes
Où sont les tests ?

2022-07-11 10:24 UTC, JeremyPayet commented on src/main/java/digi/gdt/repository/CarpoolRepository.java
> +	Optional<Carpool> findById(Integer id);
Si je me rappelle bien, la fonction était déjà là.
Je l'ai enlevé, du coup.

2022-07-11 10:24 UTC, JeremyPayet commented on src/main/java/digi/gdt/service/UserService.java
> +		// TODO Auto-generated method stub
Fait

2022-07-11 10:24 UTC, JeremyPayet commented on src/main/java/digi/gdt/controller/CarpoolController.java
> +	public CarpoolController(CarpoolService carpool, UserService userSrv) {
J'ai homogénéisé en mettant bien carpoolSrv

2022-07-11 10:25 UTC, JeremyPayet commented on src/main/java/digi/gdt/controller/CarpoolController.java
> +	private UserService userSrv;
Fait

2022-07-11 10:26 UTC, JeremyPayet commented on src/main/java/digi/gdt/controller/CarpoolController.java
> +	}
La fonction a été déplacé dans UserController.

2022-07-13 11:55 UTC, JeremyPayet commented
> Où sont les tests ?

Tests unitaires faits.

2022-07-13 12:53 UTC, Axurynn approved these changes

2022-07-13 13:24 UTC, merged